# Generated by Django 4.2.3 on 2023-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default='что угодно', max_length=100, verbose_name='тест поле'),
        ),
    ]
